# Traefik v3 static configuration
# yaml-language-server: $schema=https://www.schemastore.org/traefik-v3.json

# Global
api:
  dashboard: true
  insecure: true

certificatesResolvers:
  cloudflare:
    acme:
      email: '{{ env "CLOUDFLARE_DNS_USERNAME" }}'
      storage: /var/traefik/certs/cloudflare-acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      keyType: EC256
      dnsChallenge:
        provider: cloudflare
        resolvers:
        - "1.1.1.1:53"
        - "1.0.0.1:53"

docker:
  network: '{{ env "OTTOINFO_NETWORK_NAME" }}'

global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
          permanent: true
  https:
    address: ":443"

ping:
  terminatingStatusCode: 204

serversTransport:
  insecureSkipVerify: true

# Logging - DEBUG, PANIC, FATAL, ERROR (default), WARN, INFO
log:
  level: DEBUG
  filePath: "/var/log/traefik/traefik.log"
  format: json
accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json
maxBackups: 3
