# Usage
#   Start:          docker compose up
#   Stop:           docker compose down
#   Destroy:        docker compose down -v

include:
  # APPS
  - path: ./frontendServices/portfolioUI/docker-compose.yaml
  # TRAEFIK
  - path: ./traefik-proxy/docker-compose.yaml # Reverse Proxy
  # BACKEND
  # FRONTEND
  # ADDITIONAL

# Create/Setup Networks
networks:
  # If no other networks are defined on the service, it will be in "default" network by default
  ottoinfo:
    name: ${OTTOINFO_NETWORK_NAME}
    driver: ${OTTOINFO_NETWORK_DRIVER}

# Secrets for Production
secrets:
  cloudflare_dns_api_token:
    file: ./secrets/cloudflare_dns_api_token.txt
  cloudflare_dns_username:
    file: ./secrets/cloudflare_dns_username.txt
  traefik_dashboard_credentials:
    file: ./secrets/traefik_dashboard_credentials.txt
