services:
  error-pages:
    image: tarampampam/error-pages
    container_name: ${ERROR_NAME}
    hostname: ${ERROR_NAME}
    restart: unless-stopped
    environment:
      - TEMPLATE_NAME=${ERROR_TEMPLATE}
      - TZ=${TZ}
    ports:
      - "${ERROR_HTTP_PORT_FORWARD}:${ERROR_HTTP_PORT}"
    networks:
      - ottoinfo
    labels:
      # Orb Stack
      - dev.orbstack.domains=${ERROR_SUB_DOMAIN}.orb.local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
