services:
  postgres:
    image: postgres
    container_name: ${POSTGRES_SERVICE_NAME}
    hostname: ${POSTGRES_SERVICE_NAME}
    environment:
    - TZ=${TZ}
    - POSTGRES_DB=${POSTGRES_DATABASE}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_USER=${POSTGRES_USER}
    - DEPLOY_ENV=local
    networks:
      services:
        ipv4_address: ${POSTGRES_SERVICE_IP4} # Static IP
    ports:
    - "${POSTGRES_SERVICE_PORT_FORWARD}:${POSTGRES_SERVICE_PORT}"
    volumes:
    - pgdata:/var/lib/postgresql/data
    labels:
    # Orb Stack
    - dev.orbstack.domains=${POSTGRES_SUB_DOMAIN}.ottoinfo.local
    # - dev.orbstack.http-port=${POSTGRES_SERVICE_PORT}
    #  Traefik
    - traefik.enable=true

volumes:
  pgdata:
